import subprocess
import time

from fastapi.testclient import TestClient


def test_plan_implementation_diff_and_main_checkout_isolation(
    client: TestClient, app, monkeypatch, caplog
) -> None:
    monkeypatch.setenv("FAKE_CODEX_SCENARIO", "success")
    response = client.post("/api/repos", json={"mode": "create", "name": "implementation-target"})
    assert response.status_code == 201
    repository = response.json()["repository"]
    created = client.post(
        "/api/jobs",
        headers={"Idempotency-Key": "implementation-test"},
        json={"request_text": "Create a small fixture", "repository_id": repository["id"]},
    )
    assert created.status_code == 202
    job_id = created.json()["job"]["id"]
    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        detail = client.get(f"/api/jobs/{job_id}").json()
        if detail["status"] in {"COMPLETED", "FAILED"}:
            break
        time.sleep(0.05)
    stderr_path = app.state.settings.home / "data" / "jobs" / job_id / "codex.stderr"
    stderr = stderr_path.read_text(encoding="utf-8") if stderr_path.exists() else "not launched"
    assert detail["status"] == "COMPLETED", f"{detail}; fake Codex stderr={stderr}; logs={caplog.text}"
    assert detail["codex_thread_id"] == "fake-thread-001"
    assert detail["diff_paths"] == ["fake-implementation.txt"]
    assert "+generated by fake codex" in detail["diff"]
    assert any(event["type"] == "file.changed" for event in detail["events"])
    status = subprocess.run(
        ["git", "-C", repository["path"], "status", "--porcelain"], check=True, capture_output=True, text=True
    )
    assert status.stdout == ""


def test_codex_reported_write_outside_worktree_fails_job(client: TestClient, monkeypatch) -> None:
    monkeypatch.setenv("FAKE_CODEX_SCENARIO", "outside")
    response = client.post("/api/repos", json={"mode": "create", "name": "outside-target"})
    assert response.status_code == 201, response.text
    repository = response.json()["repository"]
    created = client.post(
        "/api/jobs",
        headers={"Idempotency-Key": "outside-test"},
        json={"request_text": "Make a change", "repository_id": repository["id"]},
    )
    job_id = created.json()["job"]["id"]
    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        detail = client.get(f"/api/jobs/{job_id}").json()
        if detail["status"] in {"COMPLETED", "FAILED"}:
            break
        time.sleep(0.05)
    assert detail["status"] == "FAILED"
    assert detail["diff_paths"] == []


def test_two_jobs_on_one_repo_run_in_distinct_worktrees(client: TestClient, monkeypatch) -> None:
    monkeypatch.setenv("FAKE_CODEX_SCENARIO", "parallel")
    monkeypatch.setenv("FAKE_PLAN_DELAY", "1")
    repository = client.post("/api/repos", json={"mode": "create", "name": "parallel-target"}).json()[
        "repository"
    ]
    jobs = [
        client.post(
            "/api/jobs",
            headers={"Idempotency-Key": f"parallel-{index}"},
            json={"request_text": f"Implement {index}", "repository_id": repository["id"]},
        ).json()["job"]
        for index in range(2)
    ]
    details = []
    deadline = time.monotonic() + 60
    while time.monotonic() < deadline:
        details = [client.get(f"/api/jobs/{job['id']}").json() for job in jobs]
        if all(detail["status"] in {"COMPLETED", "FAILED"} for detail in details):
            break
        time.sleep(0.05)
    assert all(detail["status"] == "COMPLETED" for detail in details)
    assert len({detail["worktree_path"] for detail in details}) == 2
    assert len({detail["branch"] for detail in details}) == 2
    summaries = [
        step["summary"]["summary"]
        for detail in details
        for step in detail["steps"]
        if step["kind"] == "implement"
    ]
    assert summaries == ["concurrent", "concurrent"], details
